#!/usr/bin/sh
# writhdeck -- lanceur : uxncli (le device Console d'uxn) ne touche pas
# lui-meme aux reglages du terminal (raw mode, echo) -- meme limite que
# kibi.tal (voir sa propre etiquette "kibi", TODO "Make emulator change
# to raw mode."), meme remede ici : desactiver icanon/echo avant de
# lancer le rom, restaurer apres (meme si le rom quitte en erreur).
DIR=$(dirname "$0")

TTY=`stty -g`
stty -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon \
     -ixoff -icanon onlcr -echo -isig -iuclc -ixany -imaxbel -xcase min 1 time 0

uxncli "$DIR/bin/writhdeck.rom" "$@"
EXIT=$?

stty $TTY
exit $EXIT
